# Generated by Django 3.1.7 on 2021-04-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('INTERNSHIP', 'internship'), ('PLACEMENT', 'placement')], max_length=30)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('skills', models.TextField()),
                ('description', models.TextField(null=True)),
                ('industry', models.CharField(max_length=100)),
                ('branch_restriction', models.BooleanField(default=False)),
                ('branches', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
