# Generated by Django 3.1.7 on 2021-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('INTERNSHIP', 'internship'), ('PLACEMENT', 'placement')], max_length=30)),
                ('date_posted', models.DateTimeField()),
                ('skills', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
    ]
