# Generated by Django 3.1.7 on 2021-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210401_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
