# Generated by Django 3.1.7 on 2021-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210401_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='branches',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
