# Generated by Django 3.1.7 on 2021-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210401_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(max_length=500),
        ),
    ]
