# Generated by Django 3.1.7 on 2021-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
