# Generated by Django 3.1.7 on 2021-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('COMPANY', 'Company'), ('ALUMNI', 'Alumni'), ('ADMIN', 'Admin'), ('SUPERUSER', 'SuperUser')], max_length=30),
        ),
    ]
